[0m17:33:42.351665 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01d0adb4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01d1c56850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01cf94bed0>]}


============================== 17:33:42.353984 | b94e9ef6-9b6a-4ef4-8c56-e7bad8dce430 ==============================
[0m17:33:42.353984 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:33:42.354415 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/camilajaviera/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init transformations', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:33:42.359973 [debug] [MainThread]: Starter project path: /home/camilajaviera/.local/lib/python3.13/site-packages/dbt/include/starter_project
[0m17:33:42.362474 [info ] [MainThread]: 
Your new dbt project "transformations" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:33:42.362763 [info ] [MainThread]: Setting up your profile.
[0m17:34:18.124123 [info ] [MainThread]: Profile transformations written to /home/camilajaviera/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:34:18.125003 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 35.80907, "process_in_blocks": "0", "process_kernel_time": 0.119716, "process_mem_max_rss": "94568", "process_out_blocks": "208", "process_user_time": 0.829772}
[0m17:34:18.125416 [debug] [MainThread]: Command `dbt init` succeeded at 17:34:18.125341 after 35.81 seconds
[0m17:34:18.125727 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01cf9bf490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01cfe6b770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f01cf8346b0>]}
[0m17:34:18.126044 [debug] [MainThread]: Flushing usage events
[0m17:34:18.966188 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:45:36.080705 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27cec134d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27cffea850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27cdc83ed0>]}


============================== 11:45:36.084034 | c1c31750-f494-43cd-9406-ecfe2e278a6b ==============================
[0m11:45:36.084034 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:45:36.084447 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/camilajaviera/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run -s employees_resume', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:45:36.084826 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/camilajaviera/Documentos/github/dbt-transformations-sql-mock-data/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:45:36.085668 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.040219966, "process_in_blocks": "28496", "process_kernel_time": 0.164092, "process_mem_max_rss": "90188", "process_out_blocks": "16", "process_user_time": 0.830974}
[0m11:45:36.086046 [debug] [MainThread]: Command `dbt run` failed at 11:45:36.085974 after 0.04 seconds
[0m11:45:36.086327 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27cdd57820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27cdca9010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f27cdd85370>]}
[0m11:45:36.086605 [debug] [MainThread]: Flushing usage events
[0m11:45:37.307791 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:05:16.022415 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb95dc174d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb95efca850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb95cc83ed0>]}


============================== 12:05:16.024769 | e71efeb4-cdd4-40a7-ad87-d5ec0b7a5866 ==============================
[0m12:05:16.024769 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:05:16.025287 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/camilajaviera/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --profiles-dir /home/camilajaviera/.dbt --profile transformations_bigquery', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:05:16.025716 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/camilajaviera/Documentos/github/dbt-transformations-sql-mock-data/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:05:16.026641 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.039785482, "process_in_blocks": "0", "process_kernel_time": 0.12669, "process_mem_max_rss": "90304", "process_out_blocks": "8", "process_user_time": 0.810031}
[0m12:05:16.027185 [debug] [MainThread]: Command `dbt run` failed at 12:05:16.027093 after 0.04 seconds
[0m12:05:16.027591 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb95cd57820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb95cca9010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb95cd85370>]}
[0m12:05:16.028041 [debug] [MainThread]: Flushing usage events
[0m12:05:17.410679 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:08:07.684240 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7f7a9f34d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7f7bb6e850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7f79863ed0>]}


============================== 12:08:07.686616 | c60690cc-20af-4efc-9b10-93708bb3940f ==============================
[0m12:08:07.686616 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:08:07.687073 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/camilajaviera/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --profiles-dir /home/camilajaviera/.dbt --profile transformations_bigquery', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:08:07.687458 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/camilajaviera/Documentos/github/dbt-transformations-sql-mock-data/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:08:07.688144 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.039474867, "process_in_blocks": "0", "process_kernel_time": 0.111693, "process_mem_max_rss": "90184", "process_out_blocks": "8", "process_user_time": 0.812449}
[0m12:08:07.688571 [debug] [MainThread]: Command `dbt run` failed at 12:08:07.688482 after 0.04 seconds
[0m12:08:07.688907 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7f79937820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7f79889010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7f79969370>]}
[0m12:08:07.689233 [debug] [MainThread]: Flushing usage events
[0m12:08:08.512546 [debug] [MainThread]: An error was encountered while trying to flush usage events
